[package]
name = "dying_light_hack"
version = "0.1.2"
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
vcheat = "=0.6.4"
hudhook-mini = { version = "=0.6.5", default-features = false, features = [
    "dx11",
] }
